package:
  name: neuvector-scanner
  version: "3.876"
  epoch: 0
  description: NeuVector vulnerability scanner for the SUSE NeuVector Container Security Platform
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates
      - neuvector-scanner-task
      - neuvector-sigstore-interface
    provides:
      - neuvector-db
      - neuvector-scanner-monitor

environment:
  contents:
    packages:
      - busybox
      - crane

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/scanner
      tag: v${{package.version}}
      expected-commit: 961f138e7b09842cee122dac5fdf68ee7c3ff0a2

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: scanner
      prefix: usr/local
      vendor: true

  # Empty file that tells NV that the scanner is running in a container
  - runs: touch ${{targets.contextdir}}/usr/local/bin/.nvcontainer

  - uses: strip

subpackages:
  - name: ${{package.name}}-task
    description: NeuVector Scanner Task
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: .
          output: scannerTask
          prefix: usr/local
          vendor: true

  # Need a separate monitor subpackage for neuvector/scanner/monitor different from neuvector/neuvector/monitor
  - name: ${{package.name}}-monitor
    description: NeuVector Scanner Monitor
    pipeline:
      - runs: |
          make -C monitor
          mkdir -p ${{targets.contextdir}}/usr/local/bin
          install -Dm755 monitor/monitor ${{targets.contextdir}}/usr/local/bin/monitor

  - name: neuvector-db
    description: NeuVector vulnerability database for the SUSE NeuVector Container Security Platform
    pipeline:
      - runs: |
          # Fetch NeuVector scanner from docker hub
          # https://hub.docker.com/r/neuvector/scanner/tags
          # we don't use the dbgen tool for this since it's very slow and 
          # super flaky. Extracting is faster and is more reliable.
          # This may change in the future if neuvector isn't published to DH
          crane export neuvector/scanner:${{package.version}} scanner.tar

          # Extract image
          mkdir -p scanner
          tar xvf scanner.tar -C scanner

          # Install DB
          mkdir -p ${{targets.contextdir}}/etc/neuvector/db
          cp scanner/etc/neuvector/db/cvedb ${{targets.contextdir}}/etc/neuvector/db/cvedb
    test:
      pipeline:
        - runs: |
            if [[ -f "/etc/neuvector/db/cvedb" ]]; then
              echo "CVE DB found!" && exit 0
            else
              echo "CVE DB not found!" && exit 1
            fi

test:
  pipeline:
    - runs: |
        if scanner --help | grep -q "usage: scan [OPTIONS]"; then
            exit 0
        fi

update:
  enabled: true
  schedule:
    period: daily
    reason: NeuVector scanner is updated daily for database updates
  git:
    tag-filter-prefix: v
    strip-prefix: v
